### ISSUE TITLE
Mod Updates/Add/Remove 6/9/16

### ISSUE THREAD

**Issue by MrNinja93** [timstableford/MinecraftConfigs#2]
**Update**
Biomes O Plenty to 2082
BloodMagic - 1.9.4-2.0.4-58 (**version included is 1.7.10!**)
Chisel MC1.9.4-0.0.6.33 (**version included is 1.7.10!**)
StorageDrawers-1.10.2-3.2.7
Tinkers Construct-1.10.2-2.4.0

**Add**
Baubles: 1.9.4-1.2.1.0 
Guide-API-1.10.2-2.0.2-45 (Blood magic dependency) 
Simpleretrogen -1.10-4.0.1+8

**Maybe**
Compact Solars? Ic2 solar power: latest version -1.10.2-5.0.4.328-universal
Roots-1.10.2-0.201.0
FastLeafDecay-v11

**Remove**
Defense tech **Only exists in 1.7.10!**

**FB suggestions opinion**

- Chunk edge indicator, Vanilla has the functionallity but its awkward in the F3+G Debug menu thing Chunk edge just adds it as NEI did with F9

- Veinminer Have no opinion for or against, I use it in Singleplayer just for convenience.

- Craftable elytra -  Have no opinion for or against. Glider functionality already exists in EnderIO using Dark steel armour though.

- Railcraft - Doesn't currently exist in 1.10.2 port in progress (Alternative rail network mod exists- signals if people want some form of intelligent minecart management)

- Magical Crops also doesn't exist in 1.10.2 

- Draconic Evolution - inadvisable at this time, highly unstable/extreme alpha state.

**Comment by MrNinja93** [comment]
RfTools control Just released will investigate/test, Mcjty usually releases stable mods. 
Similar to Steve's factory manager from 1.7.10

**Comment by timstableford** [comment]
Not going to update Tinkers Construct. The version I downloaded is a release, the one you mentioned is Beta.

**Comment by timstableford** [comment]
Everything else has been updated, I've also added Craftable Elytra and updated the configs.
