### ISSUE TITLE
Do we want these features? pic attached

### ISSUE THREAD

**Issue by MrNinja93** [timstableford/MinecraftConfigs#5]
caverns that sporadically spawn with grass/trees inside
I know the mod that's adding it, easy to disable.

![2016-09-07_22 24 46](https://cloud.githubusercontent.com/assets/21979276/18329140/024a4b16-754a-11e6-9156-b9497e8bf7b3.png)

**Comment by timstableford** [comment]
I like it, would be fun to build a little shack in, keep it :)
